version: '3.9'

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
        DATABASE_URI: ${DATABASE_URI}
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
        CRON_SECRET: ${CRON_SECRET}
        PREVIEW_SECRET: ${PREVIEW_SECRET}
        S3_BUCKET: ${S3_BUCKET}
        S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
        S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
        S3_REGION: ${S3_REGION}
        S3_ENDPOINT: ${S3_ENDPOINT}
    image: zad-web:runner
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: unless-stopped

  # postgres:
  #   image: postgres:16-alpine
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-postgres}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  #     POSTGRES_DB: ${POSTGRES_DB:-app}
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER']
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   # Expose to host only if needed
  #   # ports:
  #   #   - '5432:5432'
# volumes:
# pgdata:
